import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";
import AppProvider from "@/components/providers/AppProvider";
import { Nunito_Sans } from "next/font/google";
import Script from "next/script";
import TranslateProvider from "@/components/providers/TranslateProvider";
import LangConfig from "./lang-config";
import { Suspense } from "react";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-nunito",
});

const FIXED_TITLE = "Conwalls";

export const metadata: Metadata = {
  title: FIXED_TITLE,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const titleGuardScript = `
    (function () {
      var FIXED_TITLE = ${JSON.stringify(FIXED_TITLE)};

      function setFixedTitle() {
        if (document.title !== FIXED_TITLE) {
          document.title = FIXED_TITLE;
        }

        var titleEl = document.querySelector("head > title");
        if (titleEl && titleEl.textContent !== FIXED_TITLE) {
          titleEl.textContent = FIXED_TITLE;
        }
      }

      setFixedTitle();

      if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", setFixedTitle);
      } else {
        setFixedTitle();
      }

      window.addEventListener("load", setFixedTitle);
      window.addEventListener("pageshow", setFixedTitle);
      document.addEventListener("visibilitychange", function () {
        if (!document.hidden) setFixedTitle();
      });

      var headObserver = new MutationObserver(function () {
        setFixedTitle();
      });

      var startObserver = function () {
        if (document.head) {
          headObserver.observe(document.head, {
            childList: true,
            subtree: true,
            characterData: true,
          });
        }
      };

      startObserver();

      setInterval(setFixedTitle, 1000);
    })();
  `;

  return (
    <html lang="de" className={nunito.variable}>
      <head>
        <meta name="google" content="notranslate" />
        <Script
          id="fixed-title-guard"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: titleGuardScript }}
        />
      </head>

      <body className="font-nunito antialiased">
        <AuthProvider>
          <AppProvider>
            <div id="google_translate_element"></div>

            <Suspense fallback={null}>
              <LangConfig />
            </Suspense>

            <Suspense fallback={null}>
              <TranslateProvider />
            </Suspense>

            {children}

            <Script
              src="//translate.google.com/translate_a/element.js?cb=TranslateInit"
              strategy="afterInteractive"
            />

            <Toaster />
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}













// import type { Metadata } from "next";
// import "./globals.css";
// import { Toaster } from "@/components/ui/sonner";
// import AuthProvider from "@/components/providers/AuthProvider";
// import AppProvider from "@/components/providers/AppProvider";

// import { Nunito_Sans } from "next/font/google";
// import Script from "next/script";
// import TranslateProvider from "@/components/providers/TranslateProvider";
// import LangConfig from "./lang-config";
// import { Suspense } from "react";
// // import DashboardHeader from "./(participants)/_components/dashboard-header";

// const nunito = Nunito_Sans({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700", "800"],
//   variable: "--font-nunito",
// });

// export const metadata: Metadata = {
//   title: "Conwalls",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={nunito.variable}>
//       <head>
//         <title translate="no">Conwalls</title>
//       </head>

//       <body className={`font-nunito antialiased`}>
//         <AuthProvider>
//           <AppProvider>
//             {/* ✅ Google translate container */}
//             <div id="google_translate_element"></div>

//             {/* ✅ Loaded only on client */}
//             <Suspense fallback={null}>
//               <LangConfig />
//             </Suspense>
//             <Suspense fallback={null}>
//               <TranslateProvider />
//             </Suspense>

//             {/* Load Google Translate script after components are ready */}
//             {/* <Script
//               src="//translate.google.com/translate_a/element.js?cb=TranslateInit"
//               strategy="lazyOnload"
//             /> */}

//             {children}

//             {/* ✅ Load google script after client ready */}
//             <Script
//               src="//translate.google.com/translate_a/element.js?cb=TranslateInit"
//               strategy="afterInteractive"
//             />
//             <Toaster />
//           </AppProvider>
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }
